### ISSUE TITLE
1-Click "Add to Dialogflow" error

### ISSUE THREAD

**Issue by xuaninbox** [dialogflow/fulfillment-faq-nodejs#1]
when using the 1-Click "Add to Dialogflow" it gives this error

> Something went wrong. Please refresh the page.
> 
> No intents or entities found in file. Make sure that file is a zip archive and that intents and entities are in json format and are located inside intents and entities folders correspondingly.

**Comment by findzaatar** [comment]
Thanks for letting us know! We're working to fix this soon

**Comment by romankk** [comment]
Same here.

**Comment by morozru** [comment]
>           Same here.

Was able to create it manually.
1.  Enable beta features and APIs in dialogflow Agent "Settings"
2. Import "fulfillment-faq-nodejs/dialogflow-agent.zip" in to Settings>Import and Export>Import from Zip

**Comment by findzaatar** [comment]
The issue is now fixed.
